#include <TCanvas.h>
#include <TChain.h>
#include <TFile.h>
#include <TH2.h>
#include <TROOT.h>
#include <TStyle.h>
#include <iostream>
// Header file for the classes stored in the TTree if any.
using namespace std;

int main(int argc, char* argv[]) {
    // Example of Root macro to copy a subset of a Tree to a new Tree
    // Only selected entries are copied to the new Tree.
    // The input file has been generated by the program in $ROOTSYS/test/Event
    // with   Event 1000 1 99 1
    //Author: Rene Brun

    //TString dir = "root://cmseos.fnal.gov//eos/uscms/store/user/qliphy/ori/";
    TString dir        = "/eos/uscms/store/user/qliphy/ori/";
    TString infilename = argv[1];
    TString outname    = "pre" + infilename;
    std::cout << outname << std::endl;

    //Get old file, old tree and set top branch address
    TFile*   oldfile  = TFile::Open(dir + infilename);
    TTree*   oldtree  = (TTree*)oldfile->Get("demo");
    Long64_t nentries = oldtree->GetEntries();

    double ptlep1, etalep1, MET_et, mtVlepJECnew;
    oldtree->SetBranchAddress("ptlep1", &ptlep1);
    oldtree->SetBranchAddress("etalep1", &etalep1);
    oldtree->SetBranchAddress("MET_et", &MET_et);
    oldtree->SetBranchAddress("mtVlepJECnew", &mtVlepJECnew);

    //Create a new file + a clone of old tree in new file
    TFile* newfile = TFile::Open("./preslec" + outname, "recreate");
    TTree* newtree = oldtree->CloneTree(0);

    for (Long64_t i = 0; i < nentries; i++) {
        oldtree->GetEntry(i);
        bool preselec = ptlep1 > 25. && abs(etalep1) < 2.5 && MET_et < 20 && mtVlepJECnew > 30;
        if (preselec)
            newtree->Fill();
    }
    newtree->Write();
    newfile->Close();
    delete oldfile;
    delete newfile;
    return 0;
}

// compile: g++ -o selec `root-config --cflags --glibs` main.cpp preselec.cpp
