#!/bin/bash
voms-proxy-init --voms cms

crab status -d crab_SEle16B-v1
crab status -d crab_SEle16E-v1
crab status -d crab_SEle16C-v1
crab status -d crab_SEle16D-v1
crab status -d crab_SEle16F-v1
crab status -d crab_SEle16G-v1
crab status -d crab_SEle16H-v1
crab status -d crab_SEle16H-v2
crab status -d crab_SMu16C-v1
crab status -d crab_SMu16D-v1
crab status -d crab_SMu16E-v1
crab status -d crab_SMu16F-v1
crab status -d crab_SMu16G-v1
crab status -d crab_SMu16H-v1
crab status -d crab_SMu16H-v2
crab status -d crab_SMu16B-v1
crab status -d crab_DY-1
crab status -d crab_DY-2
crab status -d crab_DY-3
crab status -d crab_DY-4
crab status -d crab_STs-1
crab status -d crab_STt-1
crab status -d crab_STtbarw-1
crab status -d crab_STtw-1
crab status -d crab_WA-1
crab status -d crab_WA-private
crab status -d crab_WAJJ-1
crab status -d crab_WW-1
crab status -d crab_WW-2
crab status -d crab_WZ-1
crab status -d crab_WZ-2
crab status -d crab_ZZ-1
crab status -d crab_ZZ-2
crab status -d crab_TTJets-1
crab status -d crab_TTJets-2
crab status -d crab_STtbar-1
crab status -d crab_WJets-1
crab status -d crab_WJets-2
